var json_1Convocatoria2018mapadecalor_14 = {
"type": "FeatureCollection",
"name": "1Convocatoria2018mapadecalor_14",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "name": "Escuelas Públicas Saludables (Parte 1)", "folders": "CSE", "descriptio": "Descripción: CSE UNC -1ª CONVOCATORIA 2018<br>Código: 201800011<br>Dependencia: Área Central - SEU<br>Línea Temática: Salud<br>Director\/a: REGINA POPELKA", "altitude": 0.0, "alt_mode": null, "time_begin": null, "time_end": null, "time_when": null, "Código": "201800011", "Código de": null, "Dependenci": "Área Central - SEU", "Dependen_1": null, "Descripci�": "CSE UNC -1ª CONVOCATORIA 2018", "Dirección": null, "Director\/a": "REGINA POPELKA", "Email": null, "Línea Tem": "Salud", "Número": null, "Sitio Web": null }, "geometry": { "type": "Point", "coordinates": [ -64.1827404, -31.33745 ] } },
{ "type": "Feature", "properties": { "name": "Escuelas Públicas Saludables (Parte 1)", "folders": "CSE", "descriptio": "Descripción: CSE UNC -1ª CONVOCATORIA 2018<br>Código: 201800011<br>Dependencia: Área Central - SEU<br>Línea Temática: Salud<br>Director\/a: REGINA POPELKA", "altitude": 0.0, "alt_mode": null, "time_begin": null, "time_end": null, "time_when": null, "Código": "201800011", "Código de": null, "Dependenci": "Área Central - SEU", "Dependen_1": null, "Descripci�": "CSE UNC -1ª CONVOCATORIA 2018", "Dirección": null, "Director\/a": "REGINA POPELKA", "Email": null, "Línea Tem": "Salud", "Número": null, "Sitio Web": null }, "geometry": { "type": "Point", "coordinates": [ -64.1790718, -31.3386561 ] } },
{ "type": "Feature", "properties": { "name": "Escuelas Públicas Saludables (Parte 1)", "folders": "CSE", "descriptio": "Descripción: CSE UNC -1ª CONVOCATORIA 2018<br>Código: 201800011<br>Dependencia: Área Central - SEU<br>Línea Temática: Salud<br>Director\/a: REGINA POPELKA", "altitude": 0.0, "alt_mode": null, "time_begin": null, "time_end": null, "time_when": null, "Código": "201800011", "Código de": null, "Dependenci": "Área Central - SEU", "Dependen_1": null, "Descripci�": "CSE UNC -1ª CONVOCATORIA 2018", "Dirección": null, "Director\/a": "REGINA POPELKA", "Email": null, "Línea Tem": "Salud", "Número": null, "Sitio Web": null }, "geometry": { "type": "Point", "coordinates": [ -64.1739451, -31.4192165 ] } }
]
}
