var json_8Convocatoria2020_1 = {
"type": "FeatureCollection",
"name": "8Convocatoria2020_1",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "name": "Huertas Agroecológicas y Vínculos Saludables (3ra parte)", "folders": "CSE", "descriptio": "Descripción: CSE UNC -8ª Convocatoria 2020<br>Código: 202000388<br>Dependencia: Área Central - SEU<br>Línea Temática: Salud<br>Director\/a: ROMINA BOCCO", "altitude": 0.0, "alt_mode": null, "time_begin": null, "time_end": null, "time_when": null, "Código": "202000388", "Código de": null, "Dependenci": "Área Central - SEU", "Dependen_1": null, "Descripci�": "CSE UNC -8ª Convocatoria 2020", "Dirección": null, "Director\/a": "ROMINA BOCCO", "Email": null, "Línea Tem": "Salud", "Número": null, "Sitio Web": null }, "geometry": { "type": "Point", "coordinates": [ -64.1701279, -31.3412459 ] } },
{ "type": "Feature", "properties": { "name": "Escuelas Públicas Saludables (3ra parte)", "folders": "CSE", "descriptio": "Descripción: CSE UNC -8ª Convocatoria 2020<br>Código: 202000386<br>Dependencia: Área Central - SEU<br>Línea Temática: Salud<br>Director\/a: ROMINA BOCCO", "altitude": 0.0, "alt_mode": null, "time_begin": null, "time_end": null, "time_when": null, "Código": "202000386", "Código de": null, "Dependenci": "Área Central - SEU", "Dependen_1": null, "Descripci�": "CSE UNC -8ª Convocatoria 2020", "Dirección": null, "Director\/a": "ROMINA BOCCO", "Email": null, "Línea Tem": "Salud", "Número": null, "Sitio Web": null }, "geometry": { "type": "Point", "coordinates": [ -64.1700662, -31.3412597 ] } },
{ "type": "Feature", "properties": { "name": "Huertas Agroecológicas y Vínculos Saludables (3ra parte)", "folders": "CSE", "descriptio": "Descripción: CSE UNC -8ª Convocatoria 2020<br>Código: 202000388<br>Dependencia: Área Central - SEU<br>Línea Temática: Salud<br>Director\/a: ROMINA BOCCO", "altitude": 0.0, "alt_mode": null, "time_begin": null, "time_end": null, "time_when": null, "Código": "202000388", "Código de": null, "Dependenci": "Área Central - SEU", "Dependen_1": null, "Descripci�": "CSE UNC -8ª Convocatoria 2020", "Dirección": null, "Director\/a": "ROMINA BOCCO", "Email": null, "Línea Tem": "Salud", "Número": null, "Sitio Web": null }, "geometry": { "type": "Point", "coordinates": [ -64.178706, -31.3390932 ] } },
{ "type": "Feature", "properties": { "name": "Escuelas Públicas Saludables (3ra parte)", "folders": "CSE", "descriptio": "Descripción: CSE UNC -8ª Convocatoria 2020<br>Código: 202000386<br>Dependencia: Área Central - SEU<br>Línea Temática: Salud<br>Director\/a: ROMINA BOCCO", "altitude": 0.0, "alt_mode": null, "time_begin": null, "time_end": null, "time_when": null, "Código": "202000386", "Código de": null, "Dependenci": "Área Central - SEU", "Dependen_1": null, "Descripci�": "CSE UNC -8ª Convocatoria 2020", "Dirección": null, "Director\/a": "ROMINA BOCCO", "Email": null, "Línea Tem": "Salud", "Número": null, "Sitio Web": null }, "geometry": { "type": "Point", "coordinates": [ -64.1787944, -31.3391391 ] } },
{ "type": "Feature", "properties": { "name": "Escuelas Públicas Saludables (3ra parte)", "folders": "CSE", "descriptio": "Descripción: CSE UNC -8ª Convocatoria 2020<br>Código: 202000386<br>Dependencia: Área Central - SEU<br>Línea Temática: Salud<br>Director\/a: ROMINA BOCCO", "altitude": 0.0, "alt_mode": null, "time_begin": null, "time_end": null, "time_when": null, "Código": "202000386", "Código de": null, "Dependenci": "Área Central - SEU", "Dependen_1": null, "Descripci�": "CSE UNC -8ª Convocatoria 2020", "Dirección": null, "Director\/a": "ROMINA BOCCO", "Email": null, "Línea Tem": "Salud", "Número": null, "Sitio Web": null }, "geometry": { "type": "Point", "coordinates": [ -64.1791735, -31.3388025 ] } },
{ "type": "Feature", "properties": { "name": "Huertas Agroecológicas y Vínculos Saludables (3ra parte)", "folders": "CSE", "descriptio": "Descripción: CSE UNC -8ª Convocatoria 2020<br>Código: 202000388<br>Dependencia: Área Central - SEU<br>Línea Temática: Salud<br>Director\/a: ROMINA BOCCO", "altitude": 0.0, "alt_mode": null, "time_begin": null, "time_end": null, "time_when": null, "Código": "202000388", "Código de": null, "Dependenci": "Área Central - SEU", "Dependen_1": null, "Descripci�": "CSE UNC -8ª Convocatoria 2020", "Dirección": null, "Director\/a": "ROMINA BOCCO", "Email": null, "Línea Tem": "Salud", "Número": null, "Sitio Web": null }, "geometry": { "type": "Point", "coordinates": [ -64.1790903, -31.338798 ] } },
{ "type": "Feature", "properties": { "name": "Escuelas Públicas Saludables (3ra parte)", "folders": "CSE", "descriptio": "Descripción: CSE UNC -8ª Convocatoria 2020<br>Código: 202000386<br>Dependencia: Área Central - SEU<br>Línea Temática: Salud<br>Director\/a: ROMINA BOCCO", "altitude": 0.0, "alt_mode": null, "time_begin": null, "time_end": null, "time_when": null, "Código": "202000386", "Código de": null, "Dependenci": "Área Central - SEU", "Dependen_1": null, "Descripci�": "CSE UNC -8ª Convocatoria 2020", "Dirección": null, "Director\/a": "ROMINA BOCCO", "Email": null, "Línea Tem": "Salud", "Número": null, "Sitio Web": null }, "geometry": { "type": "Point", "coordinates": [ -64.1827848, -31.3374523 ] } },
{ "type": "Feature", "properties": { "name": "Huertas Agroecológicas y Vínculos Saludables (3ra parte)", "folders": "CSE", "descriptio": "Descripción: CSE UNC -8ª Convocatoria 2020<br>Código: 202000388<br>Dependencia: Área Central - SEU<br>Línea Temática: Salud<br>Director\/a: ROMINA BOCCO", "altitude": 0.0, "alt_mode": null, "time_begin": null, "time_end": null, "time_when": null, "Código": "202000388", "Código de": null, "Dependenci": "Área Central - SEU", "Dependen_1": null, "Descripci�": "CSE UNC -8ª Convocatoria 2020", "Dirección": null, "Director\/a": "ROMINA BOCCO", "Email": null, "Línea Tem": "Salud", "Número": null, "Sitio Web": null }, "geometry": { "type": "Point", "coordinates": [ -64.1827512, -31.3373756 ] } },
{ "type": "Feature", "properties": { "name": "Escuelas Públicas Saludables (3ra parte)", "folders": "CSE", "descriptio": "Descripción: CSE UNC -8ª Convocatoria 2020<br>Código: 202000386<br>Dependencia: Área Central - SEU<br>Línea Temática: Salud<br>Director\/a: ROMINA BOCCO", "altitude": 0.0, "alt_mode": null, "time_begin": null, "time_end": null, "time_when": null, "Código": "202000386", "Código de": null, "Dependenci": "Área Central - SEU", "Dependen_1": null, "Descripci�": "CSE UNC -8ª Convocatoria 2020", "Dirección": null, "Director\/a": "ROMINA BOCCO", "Email": null, "Línea Tem": "Salud", "Número": null, "Sitio Web": null }, "geometry": { "type": "Point", "coordinates": [ -64.1791344, -31.3386384 ] } },
{ "type": "Feature", "properties": { "name": "Huertas Agroecológicas y Vínculos Saludables (3ra parte)", "folders": "CSE", "descriptio": "Descripción: CSE UNC -8ª Convocatoria 2020<br>Código: 202000388<br>Dependencia: Área Central - SEU<br>Línea Temática: Salud<br>Director\/a: ROMINA BOCCO", "altitude": 0.0, "alt_mode": null, "time_begin": null, "time_end": null, "time_when": null, "Código": "202000388", "Código de": null, "Dependenci": "Área Central - SEU", "Dependen_1": null, "Descripci�": "CSE UNC -8ª Convocatoria 2020", "Dirección": null, "Director\/a": "ROMINA BOCCO", "Email": null, "Línea Tem": "Salud", "Número": null, "Sitio Web": null }, "geometry": { "type": "Point", "coordinates": [ -64.1791129, -31.3386046 ] } },
{ "type": "Feature", "properties": { "name": "Huertas Agroecológicas y Vínculos Saludables (3ra parte)", "folders": "CSE", "descriptio": "Descripción: CSE UNC -8ª Convocatoria 2020<br>Código: 202000388<br>Dependencia: Área Central - SEU<br>Línea Temática: Salud<br>Director\/a: ROMINA BOCCO", "altitude": 0.0, "alt_mode": null, "time_begin": null, "time_end": null, "time_when": null, "Código": "202000388", "Código de": null, "Dependenci": "Área Central - SEU", "Dependen_1": null, "Descripci�": "CSE UNC -8ª Convocatoria 2020", "Dirección": null, "Director\/a": "ROMINA BOCCO", "Email": null, "Línea Tem": "Salud", "Número": null, "Sitio Web": null }, "geometry": { "type": "Point", "coordinates": [ -64.1735734, -31.4191251 ] } },
{ "type": "Feature", "properties": { "name": "Escuelas Públicas Saludables (3ra parte)", "folders": "CSE", "descriptio": "Descripción: CSE UNC -8ª Convocatoria 2020<br>Código: 202000386<br>Dependencia: Área Central - SEU<br>Línea Temática: Salud<br>Director\/a: ROMINA BOCCO", "altitude": 0.0, "alt_mode": null, "time_begin": null, "time_end": null, "time_when": null, "Código": "202000386", "Código de": null, "Dependenci": "Área Central - SEU", "Dependen_1": null, "Descripci�": "CSE UNC -8ª Convocatoria 2020", "Dirección": null, "Director\/a": "ROMINA BOCCO", "Email": null, "Línea Tem": "Salud", "Número": null, "Sitio Web": null }, "geometry": { "type": "Point", "coordinates": [ -64.1736413, -31.4192232 ] } },
{ "type": "Feature", "properties": { "name": "Voluntariado COVID-19", "folders": "CSE", "descriptio": "Descripción: CSE UNC -8ª Convocatoria 2020<br>Código: 202000390<br>Dependencia: Facultad de Ciencias Médicas<br>Línea Temática: Salud<br>Director\/a: ROGELIO DANIEL PIZZI", "altitude": 0.0, "alt_mode": null, "time_begin": null, "time_end": null, "time_when": null, "Código": "202000390", "Código de": null, "Dependenci": "Facultad de Ciencias Médicas", "Dependen_1": null, "Descripci�": "CSE UNC -8ª Convocatoria 2020", "Dirección": null, "Director\/a": "ROGELIO DANIEL PIZZI", "Email": null, "Línea Tem": "Salud", "Número": null, "Sitio Web": null }, "geometry": { "type": "Point", "coordinates": [ -64.196746, -31.4426635 ] } },
{ "type": "Feature", "properties": { "name": "La Mejor Compra", "folders": "CSE", "descriptio": "Descripción: CSE UNC -8ª Convocatoria 2020<br>Código: 202000391<br>Dependencia: Facultad de Cs Médicas - Escuela de Nutrición<br>Línea Temática: Salud<br>Director\/a: VERÓNICA MAMONDI", "altitude": 0.0, "alt_mode": null, "time_begin": null, "time_end": null, "time_when": null, "Código": "202000391", "Código de": null, "Dependenci": "Facultad de Cs Médicas - Escuela de Nutrición", "Dependen_1": null, "Descripci�": "CSE UNC -8ª Convocatoria 2020", "Dirección": null, "Director\/a": "VERÓNICA MAMONDI", "Email": null, "Línea Tem": "Salud", "Número": null, "Sitio Web": null }, "geometry": { "type": "Point", "coordinates": [ -64.1968304, -31.4427419 ] } },
{ "type": "Feature", "properties": { "name": "Relevamiento de Viviendas de Asentamientos Humanos Irregulares en La Calera - Provincia de Córdoba. Continuidad de una experiencia académica pre profesional al servicio de la Comunidad", "folders": "CSE", "descriptio": "Descripción: CSE UNC -8ª Convocatoria 2020<br>Código: 201900221<br>Dependencia: Facultad de Arquitectura, Urbanismo y Diseño<br>Línea Temática: Educación<br>Director\/a: GLORIA BEATRIZ PEREZ DE LANZETTI", "altitude": 0.0, "alt_mode": null, "time_begin": null, "time_end": null, "time_when": null, "Código": "201900221", "Código de": null, "Dependenci": "Facultad de Arquitectura, Urbanismo y Diseño", "Dependen_1": null, "Descripci�": "CSE UNC -8ª Convocatoria 2020", "Dirección": null, "Director\/a": "GLORIA BEATRIZ PEREZ DE LANZETTI", "Email": null, "Línea Tem": "Educación", "Número": null, "Sitio Web": null }, "geometry": { "type": "Point", "coordinates": [ -64.3380887, -31.3449586 ] } }
]
}
